ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER community_mgm IDENTIFIED BY community1234;

ALTER USER community_mgm DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRant CONNECT, RESOURCE, CREATE VIEW TO community_mgm;