SELECT MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG  FROM MEMBER
WHERE MEMBER_NO =(SELECT MEMBER_NO FROM PETSITTER P
WHERE P.PETSITTER_NO = (SELECT PETSITTER_NO FROM RESERVATION
WHERE MEMBER_NO = '1'));


SELECT MEMBER_NO FROM PETSITTER P
WHERE P.PETSITTER_NO = (SELECT PETSITTER_NO FROM RESERVATION
WHERE MEMBER_NO = '1');

SELECT PETSITTER_NO FROM RESERVATION
WHERE MEMBER_NO = '1'