-- 1
SELECT EMP_ID, EMP_NAME,  PHONE, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '전지연' )
AND EMP_NAME NOT IN '전지연' ;

--2
SELECT EMP_NO, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE
                            WHERE EXTRACT(YEAR FROM  HIRE_DATE) >= 2000);

-- 3
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE
                                WHERE EMP_NAME = '노옹철')
AND JOB_CODE =  (SELECT JOB_CODE FROM EMPLOYEE
                                WHERE EMP_NAME = '노옹철')
AND EMP_NAME NOT IN '노옹철';    

-- 4
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE
                                    FROM EMPLOYEE
                                    WHERE SUBSTR(HIRE_DATE, 1, 4) = 2000)
AND JOB_CODE = (SELECT JOB_CODE
                            FROM EMPLOYEE
                            WHERE SUBSTR(HIRE_DATE, 1, 4) = 2000);


--5
SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE
                                    FROM EMPLOYEE
                                    WHERE SUBSTR(EMP_NO, 1, 2) = 77
                                    AND SUBSTR(EMP_NO, 8, 1) = 2)
AND MANAGER_ID = (SELECT MANAGER_ID
                                    FROM EMPLOYEE
                                    WHERE SUBSTR(EMP_NO, 1, 2) = 77
                                    AND SUBSTR(EMP_NO, 8, 1) = 2);
                                    
                                    
-- 6
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속 없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE HIRE_DATE IN (SELECT MIN(HIRE_DATE)
                            FROM EMPLOYEE GROUP BY DEPT_CODE);
                        

--7
SELECT EMP_ID, EMP_NAME, JOB_NAME,
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6), 'RRMMDD')) + 1  "나이",
TO_CHAR(SALARY * (1 + NVL(BONUS,0)) * 12, 'L999,999,999') "보너스포함 연봉"
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE (JOB_CODE, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6), 'RRMMDD')) + 1 )IN
(SELECT JOB_CODE, MIN(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6), 'RRMMDD')) + 1)
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
GROUP BY JOB_CODE ) ;